In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import DBSCAN
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [26]:
import os

base_path = "../Aras/House A"
txt_files = os.listdir(base_path)[:-1]

sorted_txt_files = sorted(txt_files, key=lambda x: int(x.split('_')[1].split('.')[0]))

print(sorted_txt_files)

['DAY_1.txt', 'DAY_2.txt', 'DAY_3.txt', 'DAY_4.txt', 'DAY_5.txt', 'DAY_6.txt', 'DAY_7.txt', 'DAY_8.txt', 'DAY_9.txt', 'DAY_10.txt', 'DAY_11.txt', 'DAY_12.txt', 'DAY_13.txt', 'DAY_14.txt', 'DAY_15.txt', 'DAY_16.txt', 'DAY_17.txt', 'DAY_18.txt', 'DAY_19.txt', 'DAY_20.txt', 'DAY_21.txt', 'DAY_22.txt', 'DAY_23.txt', 'DAY_24.txt', 'DAY_25.txt', 'DAY_26.txt', 'DAY_27.txt', 'DAY_28.txt', 'DAY_29.txt', 'DAY_30.txt']

In [ ]:
final_df = pd.DataFrame()

for txt in sorted_txt_files:
    data = pd.read_csv(f"{base_path}/{txt}",sep=' ', header=None)
    sensor_data = data.iloc[:, :-2].values
    
    scaler = StandardScaler()
    sensor_data_scaled = scaler.fit_transform(sensor_data)
    
    pca = PCA(n_components=5) 
    sensor_data_pca = pca.fit_transform(sensor_data_scaled)

    dbscan = DBSCAN(eps=0.4, min_samples=4)
    dbscan.fit(sensor_data_pca)
    labels = dbscan.labels_
    data['DBSCAN_Labels'] = labels
    final_df = pd.concat([final_df,data])
    print(f"{txt} done.",f" {final_df.shape}")
final_df


#DBSCAN 2
# final_df = pd.DataFrame()

# for txt in sorted_txt_files:
#     data = pd.read_csv(f"{base_path}/{txt}",sep=' ', header=None)
#     sensor_data = data.iloc[:, :-2].values
    
#     scaler = StandardScaler()
#     sensor_data_scaled = scaler.fit_transform(sensor_data)
    
#     pca = PCA(n_components=6) 
#     sensor_data_pca = pca.fit_transform(sensor_data_scaled)

#     dbscan = DBSCAN(eps=0.5, min_samples=10)
#     dbscan.fit(sensor_data_pca)
#     labels = dbscan.labels_
#     data['DBSCAN_Labels'] = labels
#     final_df = pd.concat([final_df,data])
#     print(f"{txt} done.",f" {final_df.shape}")
# final_df

DAY_1.txt done.  (86400, 23)
DAY_2.txt done.  (172800, 23)
DAY_3.txt done.  (259200, 23)
DAY_4.txt done.  (345600, 23)
DAY_5.txt done.  (432000, 23)
DAY_6.txt done.  (518400, 23)
DAY_7.txt done.  (604800, 23)
DAY_8.txt done.  (691200, 23)
DAY_9.txt done.  (777600, 23)
DAY_10.txt done.  (864000, 23)
DAY_11.txt done.  (950400, 23)
DAY_12.txt done.  (1036800, 23)
DAY_13.txt done.  (1123200, 23)
DAY_14.txt done.  (1209600, 23)
DAY_15.txt done.  (1296000, 23)
DAY_16.txt done.  (1382400, 23)
DAY_17.txt done.  (1468800, 23)
DAY_18.txt done.  (1555200, 23)
DAY_19.txt done.  (1641600, 23)
DAY_20.txt done.  (1728000, 23)
DAY_21.txt done.  (1814400, 23)
DAY_22.txt done.  (1900800, 23)
DAY_23.txt done.  (1987200, 23)
DAY_24.txt done.  (2073600, 23)
DAY_25.txt done.  (2160000, 23)
DAY_26.txt done.  (2246400, 23)
DAY_27.txt done.  (2332800, 23)
DAY_28.txt done.  (2419200, 23)
DAY_29.txt done.  (2505600, 23)
DAY_30.txt done.  (2592000, 23)

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,DBSCAN_Labels
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86395,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,2
86396,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,2
86397,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,2
86398,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,2
86399,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,2

In [28]:
(final_df["DBSCAN_Labels"]==-1).sum()

4725

In [ ]:
import pandas as pd
df = pd.read_csv("../Aras/FINAL_DBSCAN_HA.csv")

In [2]:
(df["DBSCAN_Labels"]==-1).sum()

1469