In [1]:
from sklearn.ensemble import IsolationForest
import pandas as pd

In [2]:
df = pd.read_csv("../Aras/house_a_combined_dataset.csv")

In [3]:
df.drop(columns=['Unnamed: 0',"Hour"],inplace=True)
df

,photocell_wardrobe,photocell_couch,ir_tv_receiver,force_couch_1,force_couch_2,distance_chair_1,distance_chair_2,photocell_fridge,photocell_kitchen_drawer,photocell_wardrobe_2,...,contact_bathroom_door,contact_shower_door,sonar_hall,sonar_kitchen,distance_tap,distance_water_closet,temperature_kitchen,force_bed,Resident1,Resident2
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591995,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,2
2591996,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,2
2591997,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,2
2591998,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,2
2591999,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,12,2

In [4]:
sensor_data = df.values  

model = IsolationForest(contamination=0.01)
anomalies = model.fit_predict(sensor_data)

df['anomaly'] = anomalies

In [5]:
(df['anomaly']==-1).sum()

25914