In [1]:
from sklearn.ensemble import IsolationForest
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("../Aras/House_A_Anomalies/house_a_detected_anomalies.csv")

In [3]:
dataset

,Unnamed: 0,photocell_wardrobe,photocell_couch,ir_tv_receiver,force_couch_1,force_couch_2,distance_chair_1,distance_chair_2,photocell_fridge,photocell_kitchen_drawer,...,sonar_hall,sonar_kitchen,distance_tap,distance_water_closet,temperature_kitchen,force_bed,Resident1,Resident2,Hour,Anomaly
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,12,17,0,False
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,12,17,0,False
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,12,17,0,False
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,12,17,0,False
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,12,17,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591995,86395,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,12,2,23,False
2591996,86396,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,12,2,23,False
2591997,86397,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,12,2,23,False
2591998,86398,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,12,2,23,False
2591999,86399,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,12,2,23,False

In [6]:
x = dataset.iloc[:,1:21]

In [10]:
contamination = (dataset["Anomaly"]==True).sum()/len(dataset)
contamination

0.04896913580246914

In [12]:
isf = IsolationForest(contamination=contamination)
anomaly = isf.fit_predict(x)

In [13]:
anomaly

array([1, 1, 1, ..., 1, 1, 1])

In [14]:
dataset["ISF anomaly"] = anomaly

In [17]:
(dataset["Anomaly"]==True).sum()

126928

In [18]:
(dataset["ISF anomaly"]==-1).sum()

120676

In [16]:
dataset[(dataset["Anomaly"]==True) & (dataset["ISF anomaly"]==-1)]

,Unnamed: 0,photocell_wardrobe,photocell_couch,ir_tv_receiver,force_couch_1,force_couch_2,distance_chair_1,distance_chair_2,photocell_fridge,photocell_kitchen_drawer,...,sonar_kitchen,distance_tap,distance_water_closet,temperature_kitchen,force_bed,Resident1,Resident2,Hour,Anomaly,ISF anomaly
2781,2781,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,12,15,0,True,-1
2796,2796,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,12,15,0,True,-1
2853,2853,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,12,15,0,True,-1
2878,2878,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,12,15,0,True,-1
2932,2932,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,12,15,0,True,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2587398,81798,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,15,2,22,True,-1
2587409,81809,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,15,2,22,True,-1
2587412,81812,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,15,2,22,True,-1
2587432,81832,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,15,2,22,True,-1
2588747,83147,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,27,2,23,True,-1