In [3]:
from sklearn.ensemble import IsolationForest
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv("../Aras/House_B_Anomalies/house_b_detected_anomalies.csv")

In [5]:
dataset

,Unnamed: 0.1,Unnamed: 0,contact_kitchen_cupboard_1,contact_kitchen_cupboard_2,contact_house_door,contact_wardrobe_door_1,contact_wardrobe_door_2,contact_shower_door,distance_tap,force_chair_1,...,pressure_mat_bed_1,pressure_mat_bed_2,pressure_mat_armchair,sonar_bathroom_door,sonar_kitchen,sonar_closet,Resident1,Resident2,Hour,Anomaly
0,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,0,False
1,1,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,0,False
2,2,2,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,0,False
3,3,3,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,0,False
4,4,4,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591995,2591995,86395,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,23,False
2591996,2591996,86396,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,23,False
2591997,2591997,86397,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,23,False
2591998,2591998,86398,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,23,False
2591999,2591999,86399,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,11,11,23,False

In [6]:
x = dataset.iloc[:,1:21]

In [7]:
contamination = (dataset["Anomaly"]==True).sum()/len(dataset)
contamination

0.02671489197530864

In [8]:
isf = IsolationForest(contamination=contamination)
anomaly = isf.fit_predict(x)

In [9]:
anomaly

array([1, 1, 1, ..., 1, 1, 1])

In [10]:
dataset["ISF anomaly"] = anomaly

In [11]:
(dataset["Anomaly"]==True).sum()

69245

In [12]:
(dataset["ISF anomaly"]==-1).sum()

68893

In [13]:
dataset[(dataset["Anomaly"]==True) & (dataset["ISF anomaly"]==-1)]

,Unnamed: 0.1,Unnamed: 0,contact_kitchen_cupboard_1,contact_kitchen_cupboard_2,contact_house_door,contact_wardrobe_door_1,contact_wardrobe_door_2,contact_shower_door,distance_tap,force_chair_1,...,pressure_mat_bed_2,pressure_mat_armchair,sonar_bathroom_door,sonar_kitchen,sonar_closet,Resident1,Resident2,Hour,Anomaly,ISF anomaly
40471,40471,40471,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4,4,11,True,-1
40583,40583,40583,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4,4,11,True,-1
40842,40842,40842,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4,4,11,True,-1
40904,40904,40904,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4,4,11,True,-1
40958,40958,40958,0,0,0,0,0,0,0,1,...,0,0,0,0,0,4,4,11,True,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506226,2506226,626,0,0,0,0,0,0,0,0,...,0,0,0,0,0,12,12,0,True,-1
2506270,2506270,670,0,0,0,0,0,0,0,0,...,0,0,0,0,0,12,12,0,True,-1
2506308,2506308,708,0,0,0,0,0,0,0,0,...,0,0,0,0,0,12,12,0,True,-1
2506330,2506330,730,0,0,0,0,0,0,0,0,...,0,0,0,0,0,12,12,0,True,-1
2534350,2534350,28750,0,0,0,0,0,0,0,0,...,0,0,0,1,0,3,17,7,True,-1