In [1]:
import pandas as pd

In [2]:
dataframes=[]
for i in range(1,31):
    df = pd.read_csv(f'../Aras/House B/DAY_{i}.txt', sep=' ', header=None)
    dataframes.append(df)

In [3]:
columns = [
    "contact_kitchen_cupboard_1",   # Column 1: co1 - Contact Sensor in Kitchen cupboard
    "contact_kitchen_cupboard_2",   # Column 2: co2 - Contact Sensor in Kitchen cupboard
    "contact_house_door",           # Column 3: co3 - Contact Sensor at House Door
    "contact_wardrobe_door_1",      # Column 4: co4 - Contact Sensor at Wardrobe Door
    "contact_wardrobe_door_2",      # Column 5: co5 - Contact Sensor at Wardrobe Door
    "contact_shower_door",          # Column 6: co6 - Contact Sensor at Shower Cabinet Door
    "distance_tap",                 # Column 7: di2 - Distance Sensor at Tap
    "force_chair_1",                # Column 8: fo1 - Force Sensor on Chair
    "force_chair_2",                # Column 9: fo2 - Force Sensor on Chair
    "force_chair_3",                # Column 10: fo3 - Force Sensor on Chair
    "photocell_fridge",             # Column 11: ph1 - Photocell at Fridge
    "photocell_kitchen_drawer",     # Column 12: ph2 - Photocell at Kitchen Drawer
    "pressure_mat_couch_1",         # Column 13: pr1 - Pressure Mat on Couch
    "pressure_mat_couch_2",         # Column 14: pr2 - Pressure Mat on Couch
    "pressure_mat_bed_1",           # Column 15: pr3 - Pressure Mat on Bed
    "pressure_mat_bed_2",           # Column 16: pr4 - Pressure Mat on Bed
    "pressure_mat_armchair",        # Column 17: pr5 - Pressure Mat on Armchair
    "sonar_bathroom_door",          # Column 18: so1 - Sonar Distance Sensor at Bathroom Door
    "sonar_kitchen",                # Column 19: so2 - Sonar Distance Sensor in Kitchen
    "sonar_closet",                 # Column 20: so3 - Sonar Distance Sensor in Closet
    "Resident1",                    # Column 21: Activity labels for Resident 1
    "Resident2"                     # Column 22: Activity labels for Resident 2
]

In [4]:
activity_dict = {
    1: "Other",
    2: "Going Out",
    3: "Preparing Breakfast",
    4: "Having Breakfast",
    5: "Preparing Lunch",
    6: "Having Lunch",
    7: "Preparing Dinner",
    8: "Having Dinner",
    9: "Washing Dishes",
    10: "Having Snack",
    11: "Sleeping",
    12: "Watching TV",
    13: "Studying",
    14: "Having Shower",
    15: "Toileting",
    16: "Napping",
    17: "Using Internet",
    18: "Reading Book",
    19: "Laundry",
    20: "Shaving",
    21: "Brushing Teeth",
    22: "Talking on the Phone",
    23: "Listening to Music",
    24: "Cleaning",
    25: "Having Conversation",
    26: "Having Guest",
    27: "Changing Clothes"
}

In [5]:
for df in dataframes:
    df.columns=columns
    df['Hour'] = df.index // 3600  # Assuming each row is one second, calculate the hour of day

In [6]:
flag=1
for df in dataframes:
    missing_values = df.isnull().sum()
    if(len(missing_values[missing_values >0])):
        print(missing_values[missing_values >0])
    else:
        flag=0
if flag==0:
    print('No missing values in the dataset')

No missing values in the dataset

In [7]:
total_df=pd.DataFrame()
for df in dataframes:
    total_df=pd.concat([total_df,df])
total_df

,contact_kitchen_cupboard_1,contact_kitchen_cupboard_2,contact_house_door,contact_wardrobe_door_1,contact_wardrobe_door_2,contact_shower_door,distance_tap,force_chair_1,force_chair_2,force_chair_3,...,pressure_mat_couch_2,pressure_mat_bed_1,pressure_mat_bed_2,pressure_mat_armchair,sonar_bathroom_door,sonar_kitchen,sonar_closet,Resident1,Resident2,Hour
0,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86395,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,23
86396,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,23
86397,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,23
86398,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,23
86399,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,11,11,23

In [8]:
total_df.to_csv(path_or_buf="../Aras/house_b_combined_dataset.csv")