In [1]:
import pandas as pd

In [2]:
dataframes=[]
for i in range(1,31):
    df = pd.read_csv(f'../Aras/House A/DAY_{i}.txt', sep=' ', header=None)
    dataframes.append(df)

In [ ]:
columns = [
    "photocell_wardrobe",         # Column 1: Ph1 - Photocell in Wardrobe
    "photocell_couch",            # Column 2: Ph2 - Photocell in Convertible Couch (Resident 2's bed)
    "ir_tv_receiver",             # Column 3: Ir1 - IR Sensor at TV receiver
    "force_couch_1",              # Column 4: Fo1 - Force Sensor on Couch (1)
    "force_couch_2",              # Column 5: Fo2 - Force Sensor on Couch (2)
    "distance_chair_1",           # Column 6: Di3 - Distance Sensor at Chair (1)
    "distance_chair_2",           # Column 7: Di4 - Distance Sensor at Chair (2)
    "photocell_fridge",           # Column 8: Ph3 - Photocell at Fridge
    "photocell_kitchen_drawer",   # Column 9: Ph4 - Photocell at Kitchen Drawer
    "photocell_wardrobe_2",       # Column 10: Ph5 - Photocell in Wardrobe (another one)
    "photocell_bathroom_cabinet", # Column 11: Ph6 - Photocell at Bathroom Cabinet
    "contact_house_door",         # Column 12: Co1 - Contact Sensor at House Door
    "contact_bathroom_door",      # Column 13: Co2 - Contact Sensor at Bathroom Door
    "contact_shower_door",        # Column 14: Co3 - Contact Sensor at Shower Cabinet Door
    "sonar_hall",                 # Column 15: So1 - Sonar Distance Sensor in Hall
    "sonar_kitchen",              # Column 16: So2 - Sonar Distance Sensor in Kitchen
    "distance_tap",               # Column 17: Di1 - Distance Sensor at Tap
    "distance_water_closet",      # Column 18: Di2 - Distance Sensor at Water Closet
    "temperature_kitchen",        # Column 19: Te1 - Temperature Sensor in Kitchen
    "force_bed",                  # Column 20: Fo3 - Force Sensor on Bed
    "Resident1",                  # Column 21: Activity labels - Resident 1,
    "Resident2"                   # Column 22: Activity labels - Resident 2
]

In [4]:
activity_dict = {
    1: "Other",
    2: "Going Out",
    3: "Preparing Breakfast",
    4: "Having Breakfast",
    5: "Preparing Lunch",
    6: "Having Lunch",
    7: "Preparing Dinner",
    8: "Having Dinner",
    9: "Washing Dishes",
    10: "Having Snack",
    11: "Sleeping",
    12: "Watching TV",
    13: "Studying",
    14: "Having Shower",
    15: "Toileting",
    16: "Napping",
    17: "Using Internet",
    18: "Reading Book",
    19: "Laundry",
    20: "Shaving",
    21: "Brushing Teeth",
    22: "Talking on the Phone",
    23: "Listening to Music",
    24: "Cleaning",
    25: "Having Conversation",
    26: "Having Guest",
    27: "Changing Clothes"
}

In [5]:
for df in dataframes:
    df.columns=columns
    df['Hour'] = df.index // 3600  # Assuming each row is one second, calculate the hour of day

In [6]:
flag=1
for df in dataframes:
    missing_values = df.isnull().sum()
    if(len(missing_values[missing_values >0])):
        print(missing_values[missing_values >0])
    else:
        flag=0
if flag==0:
    print('No missing values in the dataset')

No missing values in the dataset

In [7]:
total_df=pd.DataFrame()
for df in dataframes:
    total_df=pd.concat([total_df,df])
total_df

,photocell_wardrobe,photocell_couch,ir_tv_receiver,force_couch_1,force_couch_2,distance_chair_1,distance_chair_2,photocell_fridge,photocell_kitchen_drawer,photocell_wardrobe_2,...,contact_shower_door,sonar_hall,sonar_kitchen,distance_tap,distance_water_closet,temperature_kitchen,force_bed,Resident1,Resident2,Hour
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86395,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,23
86396,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,23
86397,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,23
86398,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,23
86399,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,12,2,23

In [9]:
total_df.to_csv(path_or_buf="../Aras/house_a_combined_dataset.csv")